### ISSUE TITLE
Current Projects / Previous Projects Sections

### ISSUE THREAD

**Issue by Delgado6701** [CWDG/cwdg-website#31] opened 2014-09-25 00:50 UTC
We could add sections listing current and previous projects while giving basic information about the projects and who is working on them. The previous projects could include links to the sites themselves. It could be useful for just about anyone outside the club or inside the club who is newer and not familiar with what is going on / has been done.

**Comment by J3RN** [comment] 2015-01-19 22:15
Duplicate of #21

**Closed by J3RN** 2015-01-19 22:15 UTC
Labels: duplicate
